name: mymny
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  fluentui_system_icons: ^1.1.221
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.5
  infinite_grouped_list: ^1.2.1
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
